-- Exercise 1: Using Joins

-- Question 1
-- Write and execute a SQL query to list the school names, community names and average attendance for communities with a hardship index of 98
USE DataEngineering;

SELECT CS.NAME_OF_SCHOOL, CD.COMMUNITY_AREA_NAME, CS.AVERAGE_STUDENT_ATTENDANCE, HARDSHIP_INDEX
FROM 
	CENSUS_DATA AS CD
	LEFT JOIN CHICAGO_PUBLIC_SCHOOLS AS CS ON CD.COMMUNITY_AREA_NUMBER = CS.COMMUNITY_AREA_NUMBER
WHERE CD.HARDSHIP_INDEX = 98;


-- Question 2
-- Write and execute a SQL query to list all crimes that took place at a school. Include case number, crime type and community name
SELECT CCD.CASE_NUMBER, CCD.PRIMARY_TYPE, 
FROM
	CHICAGO_CRIME_DATA AS CCD, CS.COMMUNITY_AREA_NAME
	LEFT JOIN CHICAGO_PUBLIC_SCHOOLS AS CS ON CCD.COMMUNITY_AREA_NUMBER = CS.COMMUNITY_AREA_NUMBER
	LEFT JOIN CHICAGO_PUBLIC_SCHOOLS AS CS ON CCD.COMMUNITY_AREA_NUMBER = CS.COMMUNITY_AREA_NUMBER